In [6]:
import torch
print(torch.__version__)
print(f"GPU CUDA available: {torch.cuda.is_available()}")
print(f"GPU CUDA device count: {torch.cuda.device_count()}")

2.10.0+cpu
GPU CUDA available: False
GPU CUDA device count: 0


In [8]:
#create a tensor
torch.empty(2, 3)
type(torch.empty(2, 3))


torch.Tensor

In [ ]:
print(torch.zeros(2, 3))
print(torch.ones(2, 3))
#changable everytime randm
print(torch.rand(2, 3))
#fixed random seed
torch.manual_seed(42)
print(torch.rand(2, 3))
#identity matrix
print(torch.eye(5))
#tensor matrix with one particular value
print(torch.full((2, 3), 99))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[99, 99, 99],
        [99, 99, 99]])


In [20]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a.shape

torch.Size([2, 3])

In [21]:
a.dtype

torch.int64

In [24]:
print(torch.empty_like(a))
print(torch.zeros_like(a))
print(torch.ones_like(a))
#no float datatype of a hence rand_like code will give error   
print(torch.rand_like(a))

tensor([[293878754,         1,         1],
        [        1,         1,         1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [28]:
#assign data type to tensor
b = torch.tensor([1, 2, 3], dtype=torch.float32)
b

tensor([1., 2., 3.])

In [29]:
c = torch.tensor([1, 2, 3], dtype=torch.float64)
c

tensor([1., 2., 3.], dtype=torch.float64)

In [30]:
a.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [33]:
torch.rand_like(a, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [34]:
#mathematical operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a + b, torch.add(a, b)
a - b, torch.subtract(a, b)
a * b, torch.multiply(a, b)
a / b, torch.divide(a, b)

(tensor([0.2500, 0.4000, 0.5000]), tensor([0.2500, 0.4000, 0.5000]))

In [35]:
#negative values
-a, torch.neg(a)

(tensor([-1, -2, -3]), tensor([-1, -2, -3]))

In [36]:
torch.abs(a)

tensor([1, 2, 3])

In [40]:
#create a new tensor for mean median, mode, sum, product, max, min, standard deviation, variance , argmax, argmin
c = torch.randint(size=(2, 5), low=0, high=10, dtype=torch.float32)
print(c)
print(c.mean())
print(c.mean(dim =0))
print(c.median())
print(c.mode())
print(c.sum())
print(c.prod())
print(c.max())
print(c.min())
print(c.std())
print(c.var())
print(c.argmax())
print(c.argmin())


tensor([[5., 9., 3., 4., 9.],
        [6., 2., 0., 6., 2.]])
tensor(4.6000)
tensor([5.5000, 5.5000, 1.5000, 5.0000, 5.5000])
tensor(4.)
torch.return_types.mode(
values=tensor([9., 2.]),
indices=tensor([4, 4]))
tensor(46.)
tensor(0.)
tensor(9.)
tensor(0.)
tensor(2.9889)
tensor(8.9333)
tensor(1)
tensor(7)


In [42]:
#matrix operations
d = torch.tensor([[1, 2], [3, 4]])
e = torch.tensor([[5, 6], [7, 8]])
print(d)
print(e)
print(d @ e) #matrix multiplication
print(d.mm(e)) #matrix multiplication
print(d * e) #elementwise multiplication
print(d * 10) #scalar multiplication
print(d.T) #transpose 
print(d.t()) #transpose
print(d.transpose(0, 1)) #transpose 0 and 1 dimensions
print(d.det()) #determinant
print(d.inverse()) #inverse


tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[10, 20],
        [30, 40]])
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])


RuntimeError: linalg.det: Expected a floating point or complex tensor as input. Got Long

In [43]:
#special functions
f = torch.randint(size=(2, 5), low=-10, high=10, dtype=torch.float32)
print(f)
print(torch.abs(f))
print(torch.sqrt(f)) #gives nan for negative values
print(torch.exp(f))
print(torch.log(f)) #gives nan for negative values and zero
print(torch.sin(f))
print(torch.cos(f))
print(torch.tan(f))
print(torch.sigmoid(f))
print(torch.relu(f,))
print(torch.softmax(f, dim=0))
print(torch.softmax(f, dim=1))

tensor([[ 7.,  9., -3., -7., -7.],
        [ 4.,  3.,  7.,  0., -1.]])
tensor([[7., 9., 3., 7., 7.],
        [4., 3., 7., 0., 1.]])
tensor([[2.6458, 3.0000,    nan,    nan,    nan],
        [2.0000, 1.7321, 2.6458, 0.0000,    nan]])
tensor([[1.0966e+03, 8.1031e+03, 4.9787e-02, 9.1188e-04, 9.1188e-04],
        [5.4598e+01, 2.0086e+01, 1.0966e+03, 1.0000e+00, 3.6788e-01]])
tensor([[1.9459, 2.1972,    nan,    nan,    nan],
        [1.3863, 1.0986, 1.9459,   -inf,    nan]])
tensor([[ 0.6570,  0.4121, -0.1411, -0.6570, -0.6570],
        [-0.7568,  0.1411,  0.6570,  0.0000, -0.8415]])
tensor([[ 0.7539, -0.9111, -0.9900,  0.7539,  0.7539],
        [-0.6536, -0.9900,  0.7539,  1.0000,  0.5403]])
tensor([[ 0.8714, -0.4523,  0.1425, -0.8714, -0.8714],
        [ 1.1578, -0.1425,  0.8714,  0.0000, -1.5574]])
tensor([[9.9909e-01, 9.9988e-01, 4.7426e-02, 9.1105e-04, 9.1105e-04],
        [9.8201e-01, 9.5257e-01, 9.9909e-01, 5.0000e-01, 2.6894e-01]])
tensor([[7., 9., 0., 0., 0.],
        [4., 3., 7., 

In [48]:
#implace operations = operations that change the content of a tensor without changing its identity by adding _ to the end of the function name
g = torch.rand(2, 3)
print(g)
print(g.add(10)) #does not change g and g already eist in memeory taking its own space in memory and create new g tensor after adding 10 to g
print(g.add_(10)) #changes g permanently after adding 10 to g it will change g permanently and g will be stored in the same memory location as before but with new values after adding 10 to g
print(id(g)) #memory location of g


tensor([[0.1637, 0.7025, 0.6790],
        [0.9155, 0.2418, 0.1591]])
tensor([[10.1637, 10.7025, 10.6790],
        [10.9155, 10.2418, 10.1591]])
tensor([[10.1637, 10.7025, 10.6790],
        [10.9155, 10.2418, 10.1591]])
137123549718048


In [59]:
#copying tensors wth issues
h = torch.rand(2, 3)
i = h
print(h)
print(i)
id(h), id(i) #h and i are pointing to the same memory location

tensor([[0.0758, 0.2247, 0.0624],
        [0.1816, 0.9998, 0.5944]])
tensor([[0.0758, 0.2247, 0.0624],
        [0.1816, 0.9998, 0.5944]])


(137123549051104, 137123549051104)

In [60]:
i[0][0] = 9
print(i)
print(h) #h also changes because i and h are pointing to the same memory location 
id(h), id(i) #h and i have the same memory location

tensor([[9.0000, 0.2247, 0.0624],
        [0.1816, 0.9998, 0.5944]])
tensor([[9.0000, 0.2247, 0.0624],
        [0.1816, 0.9998, 0.5944]])


(137123549051104, 137123549051104)

In [61]:
#copying tensors without issues
j = torch.rand(2, 3)
k = j.clone()
print(j)
print(k)
k[0][0] = 9
print(k)
print(j) #j does not change because k is a clone of j and k and j are separate tensors in memory
id(j), id(k) #j and k have different memory locations

tensor([[0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600]])
tensor([[0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600]])
tensor([[9.0000, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600]])
tensor([[0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600]])


(137123549051424, 137123549974832)

In [2]:
#Tesnor using GPU
import torch
torch.cuda.is_available()
print("CUDA is available. Using GPU.")

CUDA is available. Using GPU.


In [3]:
#create a gpu tensor
device = torch.device("cuda")
l = torch.tensor([1, 2, 3], device=device)

In [5]:
#move existing tensor to GPU
m = torch.tensor([1, 2, 3])
m = m.to(device)
m

tensor([1, 2, 3], device='cuda:0')

In [6]:
#move tensor back to cpu
m = l.to("cpu")
m

tensor([1, 2, 3])

In [7]:
#cpu vs gpu
import torch, time

x = torch.randn(2000, 2000)
y = torch.randn(2000, 2000)

# CPU
t = time.time()
z = x @ y
print("CPU:", time.time() - t)

# GPU
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    torch.cuda.synchronize()

    t = time.time()
    z = x @ y
    torch.cuda.synchronize()
    print("GPU:", time.time() - t)

CPU: 0.2227482795715332
GPU: 0.13469171524047852


In [6]:
#reshaping tensors
import torch
n = torch.arange(1, 10)
n.shape
n_reshaped = n.reshape(1, 9)
print(n_reshaped)
n_flattened = n_reshaped.flatten()
print(n_flattened)

o = torch.rand(2, 3, 4)
print(o.permute(2, 0, 1)) #permute changes the order of dimensions

p = torch.rand(226, 226, 3)
print(p.unsqueeze(0).shape) #unsqueeze adds a dimension at the specified position
print(p.unsqueeze(1).shape)   
print(p.unsqueeze(2).shape) 

q = torch.rand(1, 20)
print(q.squeeze(0).shape) #squeeze removes a dimension at the specified position
print(q.squeeze(1).shape)




tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[0.6977, 0.1684, 0.0181],
         [0.1266, 0.2768, 0.8067]],

        [[0.8756, 0.8162, 0.2363],
         [0.0653, 0.2211, 0.3278]],

        [[0.5691, 0.0693, 0.9412],
         [0.1113, 0.5989, 0.0063]],

        [[0.5139, 0.3691, 0.1869],
         [0.7598, 0.1812, 0.0591]]])
torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])
torch.Size([226, 226, 1, 3])
torch.Size([20])
torch.Size([1, 20])


In [8]:
#Numpy and PyTorch bridge
#numpy to torch tensor
import numpy as np
r = np.array([1, 2, 3])
s = torch.from_numpy(r)
print(s, type(s))

#torch tensor to numpy
t = s.numpy() 
print(t, type(t))

tensor([1, 2, 3]) <class 'torch.Tensor'>
[1 2 3] <class 'numpy.ndarray'>
