{{ badge }}

In [2]:
#Autograd = automatic differentiation = computing gradients automatically
import torch
x = torch.tensor(2.0, requires_grad=True) #create a tensor with requires_grad=True to track gradients
y = x**2 + 3*x + 5 #define a function of x
print(x)
print(y)


tensor(2., requires_grad=True)
tensor(15., grad_fn=<AddBackward0>)


In [ ]:
print(y.backward()) #compute the gradients meaning compute dy/dx
print(x.grad) #print the gradient of y with respect to x that is derived from the function y = x^2 + 3x + 5 is dy/dx = 2x + 3, so when x = 2, dy/dx = 2*2 + 3 = 7

None
tensor(7.)


In [4]:
#y = x^2 calculating z = sin(y) and then calculating dz/dx
x = torch.tensor(2.0, requires_grad=True)
y = x**2
z = torch.sin(y)
print(z)
z.backward()
print(x.grad) #the gradient of z with respect to x is dz/dx = dz/dy * dy/dx = cos(y) * 2x, so when x = 2, y = 4, dz/dx = cos(4) * 2*2 = -1.5136


tensor(-0.7568, grad_fn=<SinBackward0>)
tensor(-2.6146)


In [ ]:
#what if we y.grad in previous example
print(y.grad)
#y is not a scalar, so we need to specify the gradient of y with respect to itself, which is 1.0

None


/tmp/ipykernel_25925/4242488262.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  print(y.grad)


In [7]:
#example with cgpa = 6.7 and placement not placed ie 0 and we want to calculate the loss using binary cross entropy loss function and then calculate the gradients with respect weights and bias
x = torch.tensor(6.7) #input feature
y = torch.tensor(0.0) #target label

w = torch.tensor(1.0, requires_grad=True) #weights 
b = torch.tensor(0.0, requires_grad=True) #bias

z = w * x + b #linear regression model
print(z) 
y_pred = torch.sigmoid(z) #sigmoid activation function to get the predicted probability
print(y_pred)

loss = torch.nn.functional.binary_cross_entropy(y_pred, y)
print(loss)
loss.backward() #compute the gradients of loss with respect to weights and bias
print(w.grad) #print the gradient of loss with respect to weights   
print(b.grad) #print the gradient of loss with respect to bias

tensor(6.7000, grad_fn=<AddBackward0>)
tensor(0.9988, grad_fn=<SigmoidBackward0>)
tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(6.6918)
tensor(0.9988)


In [10]:
#vector tensors and autograd
w = torch.tensor([1.0, 2.0, 3.0], requires_grad=True) #input feature vector
b = torch.tensor([0.0, 0.0, 0.0], requires_grad=True) #target labels 
z = w * x + b #linear regression model
print(z)
y_pred = torch.sigmoid(z) 
print(y_pred)
loss = torch.nn.functional.binary_cross_entropy(y_pred, y)
print(loss)
loss.backward() 
print(w.grad) 
print(b.grad)


tensor([1., 4., 9.], grad_fn=<AddBackward0>)
tensor([0.7311, 0.9820, 0.9999], grad_fn=<SigmoidBackward0>)
tensor(4.7772, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([0.2437, 0.6547, 0.9999])
tensor([0.2437, 0.3273, 0.3333])


In [30]:
#multiple time autograding can  be accumulated causing incorrect gradients, so we need to zero the gradients before computing the gradients again
w = torch.tensor(2.0, requires_grad=True)

In [ ]:
#1
v = w**2
v

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
#2
v.backward() 

In [ ]:
#3
w.grad
#if u keep running above 3 code blocks agin n agin u will see w.grad will keep geting accumulated 

tensor(8.)

In [ ]:
#OR JUST KEEP RUNNING THIS CODE BLOCK AND SEE THE GRADIENT GETTING ACCUMULATED from tensro(4.) to tensor(8.) to tensor(12.) and so on
v = w**2
v
v.backward()
w.grad

tensor(20.)

In [55]:
#hhence to avoid this we need to zero the gradients before computing the gradients again and getting only tensor(4.) as the gradient of w with respect to v
v = w**2
v
v.backward()
print(w.grad)
print(w.grad.zero_()) #zero the gradients

tensor(4.)
tensor(0.)


In [57]:
#sometime swe dont want to compute the gradients for some operations with 3 methods

# we can use torch.no_grad() context manager to disable gradient tracking for those operations
with torch.no_grad():
    w = torch.tensor(2.0, requires_grad=True)
    v = w**2
    print(v)


#we can also use detach() method to create a new tensor that shares the same data but does not require gradients
w = torch.tensor(2.0, requires_grad=True)
v = w**2
v.detach_()
print(v)

#we can also use requires_grad_() method to set requires_grad to False for those operations
w = torch.tensor(2.0, requires_grad=True)
v = w**2
v.requires_grad_(False)
print(v)



tensor(4.)
tensor(4.)


RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().